crnk:
  resourcePackage: com.lanzonprojects.omsapi.domain
  domainName: http://localhost:8081/lanzonprojects
  pathPrefix: /api/oms
  default-page-limit: 20

server:
  context-path: /lanzonprojects
  port: 8081